---
driver:
  name: docker
  use_sudo: false
#driver_plugin: docker
#driver_config:
  #require_chef_omnibus: true

platforms:
  - name: centos
    driver_config:
      image: "centos"
      platform: "rhel"
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list: 
      - recipe[thewrapper::default]
    attributes:
      lwrpsample:
        lwrpexample: 'shawarma'
        lwrp2:  'Biryani'
        msg: 'Hello I am is zakeeruddin Mohammed'
        wrapper: 'thewrapper-cookbook'

